language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.8"
  - DJANGO="django==1.9"

install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=contactBox setup.py test

after_success:
  - coverage report --omit="contactBox/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
