language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="django==1.5 --use-mirrors"
  - DJANGO="django==1.6 --use-mirrors"

install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=contactBox setup.py test

after_success:
  - coverage report --omit="contactBox/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
