language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
    - DJANGO="django>=1.8,<1.8.999"
    - DJANGO="django>=1.9,<1.9999"

install:
 - pip install -r requirements.txt
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=contactbox setup.py test

after_success:
  - coverage report --omit="contactbox/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
